version: '3.9'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx_dev
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./logs/error.log:/etc/nginx/error_log.log
        ports: 
            - 80:80
    
    auth-client:
        build: ../../client
        image: auth-client
        container_name: auth-client
        expose: 
            - 3000
        volumes: 
            - ../../client/src:/app/src
            - ../../client/public:/app/public
        environment: 
            CHOKIDAR_USEPOLLING: "true"

    auth-server:
        build: ../../server
        image: auth-server
        container_name: auth-server
        expose: 
            - 3000
        volumes: 
            - ../../server/src:/app/src
        environment: 
            CHOKIDAR_USEPOLLING: "true"

    mongo:
        image: mongo
        expose:
            - 27017
        volumes:
            - ./db-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: toor
        restart: always
